### ISSUE TITLE
[TASK] Add ink! proposals 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-rs#77]
## Overview 
We will need to add relevant ink! proposals to webbrs.

## Task Checklist

- [x] Add anchor update proposal
- [x] Fee Recipient update proposal
- [x] Maximum Deposit Limit proposal
- [x] Minimum Withdraw Limit proposal
- [x] Rescue tokens proposal
- [x] Treasury handler proposal
- [x] Add resourceID update proposal
- [x] Add tokenAdd proposal
- [x] Add tokenRemove proposal
- [x] Add wrappingFee update proposal

### Relevant Links

- [Substrate proposals](https://github.com/webb-tools/webb-rs/tree/main/proposals/src/proposal/substrate)
